name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build plugins
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends cmake ninja-build qt6-qmake qt6-base-dev libkf6kio-dev tree
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja
          ninja
          env DESTDIR=out ninja install
          tree out
