name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build plugins
    runs-on: ubuntu-latest
    container: opensuse/tumbleweed
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          zypper install -y cmake ninja "cmake(KF6KIO)" "cmake(Qt6Core)" tree
      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=RelWithDebInfo -G Ninja
          ninja
          env DESTDIR=out ninja install
          tree out
